Version: 1

sources:
<<<<<<< HEAD
  -name: SNOWFLAKE_SAMPLE_DATA
  tables: CUSTOMER
    
=======
  - name: SNOWFLAKE_SAMPLE_DATA
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: CUSTOMER
>>>>>>> 3bc426a6bd725c0f42b816e7f0acd42a61346ad8
